name: build
on: push

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Code Checkout
      - uses: actions/setup-node@v3
        name: Setup Node 14
        with:
          node-version: 14
          cache: 'npm'
